version: '2'
services:
    web:
        build: .
        #command: gunicorn -c gunicorn_conf.py flask_app:app
        command: gunicorn -c gunicorn_conf.py "flask_app:create_app(debug=True)"
        #command: python start_server.py
        volumes:
            - .:/code
        depends_on:
            - db
    db:
      image: postgres
