version: '2'
services:
    web:
        build: .
        command: gunicorn -c gunicorn_conf.py "flask_app:create_app(debug=True)"
        volumes:
            - .:/code
        depends_on:
            - db
    db:
      image: postgres
